# --------------------- graphish_urls_in_html_graphish_10_part ---------------------
graphish_urls_in_html_graphish_10_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_10_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_har_graphish_10_part ---------------------
graphish_urls_in_har_graphish_10_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_har_graphish_10_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_anchor_href_graphish_10_part ---------------------
graphish_anchor_href_graphish_10_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_anchor_href_graphish_10_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_all_related_graphish_10_part ---------------------
graphish_all_related_graphish_10_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_anchor_href_graphish_10_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_9_part ---------------------
graphish_urls_in_html_graphish_9_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_9_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_8_part ---------------------
graphish_urls_in_html_graphish_8_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_8_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_7_part ---------------------
graphish_urls_in_html_graphish_7_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_7_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_6_part ---------------------
graphish_urls_in_html_graphish_6_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_6_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_5_part ---------------------
graphish_urls_in_html_graphish_5_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_5_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_4_part ---------------------
graphish_urls_in_html_graphish_4_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_4_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_3_part ---------------------
graphish_urls_in_html_graphish_3_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_3_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- graphish_urls_in_html_graphish_2_part ---------------------
graphish_urls_in_html_graphish_2_part:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: graphish_urls_in_html_graphish_2_part
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.5,0.005,0.8
  gpu: 0
  hidden_dim: 256
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.5,0.005,0.8
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 4
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: false
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true
